### PR TITLE
Seperate H_system, add Mixer type, clean up old files

### PR DESCRIPTION
**Pull request by MSRudolph**
- `model.circuit_h` and `model.circuit_J` are now called in the circuit construction, but `model.get_h` and `model.get_J` in the energy evaluation. This allows for mismatched models.
- Added the `Mixer` type.
- Cleaned up old files and renamed

Example of Mixer usages:
`generic_mixer = GenericMixer.OneBodyMixer(n_spins)`

`custom_mixer = CustomMixer(n_spins, [[0, 1, 2], [3, 4, 5], [6, 7, 8]])`

`coherent_mixer = CoherentMixerSum([generic_mixer, CustomMixer(n_spins, [[0, 1, 2], [3, 4, 5]])], weights=[0.5, 0.5]) # partial knowledge`

`incoherent_mixer = IncoherentMixerSum([generic_mixer, CustomMixer(n_spins, [[0, 1, 2], [3, 4, 5]])], probabilities=[0.5, 0.5])`

and then:
```
quantum_enhanced_mcmc(
    n_hops=steps,
    model=model,
    mixer=your_mixer,
    gamma = 0.5, # tuple like (0.4, 0.6) also work
    initial_state=initial_state,
    temperature=1/beta,
    verbose=True
)
```

### CODE REVIEW

**Comment by MSRudolph** [comment]
Any comments @pafloxy @neelkanthrawat ?

We should merge and clean up.

**Comment by pafloxy** [comment]
I don't think we can merge as usual (can we ?) , I think we can simply retire most other branches and replace this to be the `main` branch ?

**Comment by MSRudolph** [comment]
Yes, sounds good.

**Comment by MSRudolph** [comment]
Fixed merge conflicts

**Pull request merged**
